[GOMUNGNAM] step-5 게시글 작성, 수정, 삭제 기능 구현 완료
codesquad-members-2023/be-java-cafe pull request #103
Opened 2023-03-29 04:50 UTC by KOKEONHO

어제 Hyun과 대화하다가 주소창에 사용자의 ID가 노출되는 것에 묘한 위화감을 느낀 것도 있고, 짠 코드를 다시 한번 뜯어보면서 스프링에 익숙해지는 시간을 가지고자, 사용자가 개인 정보를 수정 또는 프로필 열람 할 때 url에 사용자의 ID 대신 사용자의 고유 번호가 노출되도록 수정했습니다. 또한 Honux가 이는 지양하는게 좋을 것 같다고 수업 시간에 말씀하셨던게 떠올라 기존에 작성자를 필드로 지니고 있던 Article 클래스에서도 작성자 필드를 제거했습니다. (자세히 기억은 나지 않지만 그렇게 말씀하셨던 것 같습니다.)

이렇게 바꾸니 잘 와 닿지 않던 5단계의 요구 사항 중 하나였던 '데이터베이스 모델링' 조건도 충족할 수 있게 되었습니다. 원래는 게시글이 작성자 정보를 가지고 있었기 때문에 article 테이블과 member 테이블의 join의 필요성을 느끼지 못했지만, join 없이는 게시글 목록이나 상세 열람 시에 작성자 정보를 가지고 올 수 없음을 깨닫고 두 테이블의 join 공부를 했습니다. 아직 sql문 공부는 더 해야겠다고 느꼈습니다.

짠 코드의 대부분을 수정해야 하는 일이었지만 생각보다 재미있었고 점점 머릿 속에 동작 방식(?)이 그려지는 것 같아 뿌듯했습니다. 불필요한 작업일 수도 있겠지만 막상 하고 나니 얻은게 더 많았습니다!

2023-03-29 23:32 UTC, honux77 commented
수고하셨습니다. 공부할 때는 삽질(?)을 통해 원래 얻는 게 많아요 😅

2023-03-29 23:33 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/Constants.java
> +	}
👍

2023-03-29 23:51 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +	@GetMapping("/profile/{userSequence}")
근데 닉네임이 노출되어도 크게 상관은 없어요. GitHub도 URL에 닉네임을 노출하고 있잖아요? 뭔가 애매할 때 GitHub의 URL을 참고하는 것도 좋은 선택입니다.

2023-03-29 23:57 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +	public String userProfile(HttpSession session, @PathVariable Long userSequence, Model model) throws SQLException {
```suggestion
	public String getProfile(HttpSession session, @PathVariable Long userSequence, Model model) throws SQLException {
```

콘트롤러 메소드의 네이밍 컨벤션도 한 번 공부해 보시면 좋을 것 같아요.

2023-03-30 00:13 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +		List<ArticleWithWriterDto> articles = articleRepository.showAllArticles();
```suggestion
		List<ArticleWithWriterDto> articles = articleRepository.findAllArticles();
```

레포의 네이밍 컨벤션도 학습

2023-03-30 00:17 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/dto/ArticleWithWriterDto.java
> +	private String contents;
GET questions/list 에서 이 DTO를 이용하는데 contents가 없는 편이 더 효율적이지 않을까요?

2023-03-30 00:18 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/repository/NamedJdbcTemplateArticleRepository.java
> +		String sql = "select a.article_number, a.article_title, a.article_contents, a.article_writtentime, a.member_number, m.member_id as writer, " +
여기도 마찬가지 contents가 없으면 좋을 것 같아요.

2023-03-30 00:20 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +	@GetMapping("/qna/questions")
```suggestion
	@GetMapping("/qna/questions/form")
```

2023-03-30 00:21 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +		Article article = new Article((Long) session.getAttribute(SESSIONED_USER), title, contents);
session.getAttribute(SESSIONED_USER) 코드가 계속 중복됩니다. 요것도 줄일 수 있을까요?

2023-03-30 00:22 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +	public String saveQuestion(@RequestParam String title, @RequestParam String contents, HttpSession session) throws SQLException {
여기서도 로그인 되었는지 여부를 확인해야 하는데 안 하고 있네요.

2023-03-30 00:23 UTC, honux77 requested changes
수고하셨습니다.

1) URL 규칙을 학습하고 수정해 볼 것 
2) 콘트롤러 및 레포  메소드 이름 개선 
3) 필요한 모든 곳에 로그인 여부 검증, API 권한 확인 코드가 잘 되었는지 확인할 것

2023-03-30 01:06 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +	@GetMapping("/profile/{userSequence}")
네 처음에는 주소에 ID가 노출되는게 마냥 이상했다가 Dewey에게서 GitHub도 사용자 ID가 나온다는 말을 듣고 바꾸지 말까 고민도 했습니다. 그런데 일단 학습하는 것이 우선이라는 생각도 들고 제가 짠 코드를 방향을 잡고 고치다보면 스프링이 좀 더 익숙해지지 않을까 싶어서 수정 해봤습니다! 다음에는 Honux 말씀대로 GitHub 주소 참고해봐야겠어요.

2023-03-30 01:26 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +	public String userProfile(HttpSession session, @PathVariable Long userSequence, Model model) throws SQLException {
넵 알겠습니다

2023-03-30 01:28 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +		List<ArticleWithWriterDto> articles = articleRepository.showAllArticles();
네 안 그래도 이름 붙이는게 생각보다 어렵더군요...

2023-03-30 05:30 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/dto/ArticleWithWriterDto.java
> +	private String contents;
게시글 목록을 출력하는 questions/list에서도 이 DTO가 쓰이지만 게시글 상세 열람을 할 때에도 이 DTO가 쓰여서 contents를 뺄 수가 없습니다. 혹시 여러개의 DTO를 사용해도 상관이 없는건가요 ? 예를 들어서 questions/list에는 굳이 contents가 필요 없으니, contents가 없는 ArticleWithoutContentsDto를 만들어서 사용한다든지 ...

2023-03-30 05:57 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +	@GetMapping("/qna/questions")
수정했습니다

2023-03-30 05:57 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/repository/NamedJdbcTemplateArticleRepository.java
> +		String sql = "select a.article_number, a.article_title, a.article_contents, a.article_writtentime, a.member_number, m.member_id as writer, " +
DTO를 새롭게 만들어서 해봤습니다.

2023-03-30 06:18 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/dto/ArticleWithWriterDto.java
> +	private String contents;
맞아요. 여러개를 사용해도 상관없습니다. 뺄 수 없으면 따로 만들어야죠.

2023-03-30 07:09 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +	public String saveQuestion(@RequestParam String title, @RequestParam String contents, HttpSession session) throws SQLException {
LoginInterceptor 생성해서 로그인 여부 확인하게 해봤습니다.

2023-03-30 07:09 UTC, KOKEONHO commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +		Article article = new Article((Long) session.getAttribute(SESSIONED_USER), title, contents);
메서드로 추출해서 코드 수정해봤습니다.

2023-03-30 07:42 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +	public String saveQuestion(@RequestParam String title, @RequestParam String contents, HttpSession session) throws SQLException {
앗 그렇군요.

2023-03-30 07:43 UTC, merged