[Luke] Step1 - 구현
codesquad-members-2023/be-java-cafe pull request #36
Opened 2023-03-16 08:53 UTC by acceptor-gyu

controller에서의 메서드 이름과 repository에서의 메서드 이름이 비슷하게 만들어지는 것같은 느낌이 있어서 메서드 이름에 대한 고민이 더 필요할 것 같다.

- 스프링이 처음이나보니 공부하는데 시간을 투자하다가 미션을 구현을 급하게 하느라 고민하는 시간이 적었어서 리팩토링하는 과정에서 고민을 더 해야할 것같습니다.

2023-03-16 23:53 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    }
addViewController()를 사용해 보세요.

2023-03-16 23:54 UTC, honux77 commented on src/main/resources/templates/css/styles.css
template 디렉토리에는 css와 같은 정적 파일이 있으면 안 됩니다.

2023-03-16 23:55 UTC, honux77 requested changes
템플릿 디렉토리에 있는 static 파일들을 다 제거해서 다시 push 해 주세요.

2023-03-17 02:06 UTC, acceptor-gyu commented
다 했습니다.

2023-03-17 02:07 UTC, merged