[Hyun] step-3 구현 : DB연동 및 AWS를 사용해 배포
codesquad-members-2023/be-java-cafe pull request #46
Opened 2023-03-19 08:39 UTC by ghkdgus29

우선 테스트의 원자성과 독립성을 갖게 하기 위해 테스트용 인메모리 DB와 실제 애플리케이션 DB를 구별하였습니다.
이후 Heroku 가 유료화 되었다고하여 aws 프리티어를 이용하여 배포를 수행하였습니다.
ec2 인스턴스 내부에 mysql db 서버를 만들어 배포를 수행하였습니다.
이 과정을 통해 겪은 2가지 트러블슈팅은 다음과 같습니다.

1. RDS로 DB를 분리하지 않고, ec2 내부에 mysql DB를 설치한 경우, gradlew 빌드가 끝나지 않았습니다. 어째서 이런 동작이 일어나는지는 모르겠지만 10분 20분이 지나도 빌드가 끝나지 않기 때문에 이 방법은 불가능하다고 판단하고, 외부에서 프로젝트를 빌드한 후, ssh 로 jar 파일을 ec2 내부로 보내주는 방식을 채택하였습니다.

2. 저의 로컬 pc 에서 ec2 내부에 mysql DB와 연결할 땐 ec2 의 IP 주소를 사용하여 연결이 가능했습니다. 그러나 ec2 내부에서 ec2의 IP 주소를 사용하여 mysql DB 와 연결하려고 하면 `org.springframework.jdbc.cannotgetjdbcconnectionexception`  과 함께 연결이 실패했다는 에러로그가 발생하였습니다. 
결국 ec2 내부에서 mysql DB와 연결하기위해 ec2의 IP 주소가 아닌 localhost 를 사용하여 해결했습니다. 이 역시 왜 이런일이 일어나는지 정확히는 모르겠습니다.

처음 배포를 해보면서, 모르는게 많아 답답하고 이유를 알지 못해 답답한 점들이 많았습니다. 그래도 제가 배포한 웹사이트를 세상 어느곳에서나 접근할 수 있다고 생각하니 재밌고 보람차다는 생각도 들었습니다.

배포 URL : http://54.180.13.74:8080/

2023-03-19 23:56 UTC, honux77 commented
이후 Heroku 가 유료화 되었다고하여 aws 프리티어를 이용하여 배포를 수행하였습니다.
--> 앗 이거 다시 한 번 확인해 주실래요? 디비 없이는 될 것 같은데 확실하지 않네요.

2023-03-19 23:56 UTC, honux77 commented
ec2 인스턴스 내부에 mysql db 서버를 만들어 배포를 수행하였습니다.
--> mysql 쓰지 말고 heroku로....

2023-03-19 23:58 UTC, honux77 requested changes
MySQL 의존성 제거해 주시고 H2만으로 배포할 수 있게 수정해 주세요.

2023-03-20 06:07 UTC, ghkdgus29 commented
> MySQL 의존성 제거해 주시고 H2만으로 배포할 수 있게 수정해 주세요.

종속성 제거하였습니다!!
mysql 지우니 빌드도 잘되네요!

2023-03-20 22:22 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    private final ArticleRepository repository;
인터페이스로 바꾸셨군요. 좋습니다.

2023-03-20 22:24 UTC, honux77 commented on src/test/resources/test-schema.sql
> +    id       int         not null auto_increment primary key,
```suggestion
    id       int         primary key auto_increment ,
```
아주 소소하지만 primary key가 먼저고 not null은 불필요합니다.

2023-03-20 22:25 UTC, honux77 commented on src/test/java/kr/codesqaud/cafe/repository/H2DBUserRepositoryTest.java
> +    @DisplayName("h2 DB에서 User를 id로 조회 가능하다.")
DB test에는 @transactional을 활용하면 더 편하게 테스트 가능해요. 관련 기능 찾아보세요.

2023-03-20 22:32 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/repository/H2DBArticleRepository.java
> +package kr.codesqaud.cafe.repository;
beanPropertyRowMapper를 사용하는 대안도 있으니 검색해 보세요.

2023-03-20 22:32 UTC, honux77 approved these changes
수고하셨습니다.

2023-03-20 22:34 UTC, merged

2023-03-21 02:20 UTC, leegyeongwhan commented on src/main/java/kr/codesqaud/cafe/repository/H2DBUserRepository.java
> +    public void save(User user) {
잘먹고갑니다

2023-03-21 13:20 UTC, Gwonwoo-Nam commented on src/main/java/kr/codesqaud/cafe/repository/H2DBUserRepository.java
> +    public void save(User user) {
맛있따..!