[ManJu] Step04 구현: HttpSession을 활용한 로그인 기능 구현 / 추가기능 구현 X
codesquad-members-2023/be-java-cafe pull request #63
Opened 2023-03-22 08:18 UTC by JeonHyoChang

## 고민했던 내용
- 김영한님 강의를 통해 로그인 과정에서 [쿠키 -> 세션 -> http세션] 까지 이어지는 흐름을 자세히 알 수 있어 왜 http세션을 쓰는가 하는 고민이 해결 되었습니다.
- 예제와 다르게 파라미터로 HttpServletRequest을 받아서 사용했습니다.  HttpSession 세션까지 가는 과정을 세분화 하고 예외처리를 해주는것이 좋다 생각해서 이렇게 진행했는데, 이렇게 하는것이 좋은 코드인지 궁금합니다 ㅠ

## 설계내용
- 로그인 기능을 구현하기위한 `로그인_컨트롤러`, 홈 화면을 관리하기 위한 `홈_컨트롤러` 로 세분화
- 쿠키와 세션의 관계를 이해하고 HttpSession을 활용해 로그인 기능을 구현
- 모든 페이지의 상단부분에 해당하는 nav를 mustache if-else를 활용해 로그인 상황에 적합한 화면을 출력

## 느낀점
- 시작하기 앞서 상당히 막막한 느낌이었는데 강의를 보고 쿠키와 세션의 관계를 이해하고 진행하니 작업하기 수월한 느낌을 받았습니다.
- 스프링이 정말 편하게 작업을 이뤄준다는 점에서 스프링 에게 감동했습니다 ㅋㅋ

## aws 주소: http://13.55.133.135:8080/

2023-03-22 22:32 UTC, honux77 commented
예제와 다르게 파라미터로 HttpServletRequest을 받아서 사용했습니다. HttpSession 세션까지 가는 과정을 세분화 하고 예외처리를 해주는것이 좋다 생각해서 이렇게 진행했는데, 이렇게 하는것이 좋은 코드인지 궁금합니다 ㅠ 
-> Reqeust, Response를 직접 작성하는 것보다 Session 객체의 추상화가 가져다 주는 장점을 사용하는 게 더 좋은 코드라고 생각합니다.

2023-03-22 22:40 UTC, honux77 requested changes
1. `SimpleJdbcInsert jdbcInsert = new SimpleJdbcInsert(jdbcTemplate);` 부분을 직접 쿼리로 변경해 주세요.
2. 역시 콘트롤러 메소드의 매개변수로 HttpSession을 쓰는게 더 깔끔해 보입니다. 수정하면 좋겠어요.

공부를 해서 세션의 원리를 이해했다니 좋습니다!

2023-03-23 00:59 UTC, JeonHyoChang commented
요구사항 적용했습니다!! ㅎㅎ

2023-03-23 01:03 UTC, JeonHyoChang reviewed
요구사항 적용했습니다. ㅎㅎ

2023-03-23 01:28 UTC, merged