[nino]  step-4 구현, aws 배포
codesquad-members-2023/be-java-cafe pull request #66
Opened 2023-03-22 10:44 UTC by ninaaano

고민했던 점
- aws를 잘 몰라서 애를 많이 먹었습니다. 호눅스 강의를 다시 보면서 공부해 볼 예정입니다
- powerUser에서 ec2를 실행시켰는데 잘한건지는 모르겠습니다
- service를 따로 만들지 않아서 컨트롤러에서 많은 일을 하고 있는 것 같습니다

aws 배포 주소 :
3.35.244.240:8080

2023-03-22 23:26 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +            Optional<Member> updateUser = jdbcMemberRepository.findById(userId);
```suggestion
            Member updateUser = jdbcMemberRepository.findById(userId).orElseThrow();
```

value == null 이면 어떻게 되는거죠? 뭔가 로직이 살짝 모호해 보입니다.

2023-03-22 23:29 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +    }
여기도 실패했을 경우의 에러 처리가 명확하지 않아요.
그리고 코드품질도 조금 개선했으면 좋겠어요.

2023-03-22 23:32 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +    }
`model.addAttribute("notExist", "fail");`  는 없앨 수 있으면 없애고, 역시 Post에서 뷰를 호출하는 것도 이상합니다 ㅎㅎㅎ.

2023-03-22 23:32 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
> +        return writeDate.format(DateTimeFormatter.ofPattern("yy-MM-dd HH:mm:ss"));
👍

2023-03-22 23:33 UTC, honux77 requested changes
고민한 흔적은 많이 보이는군요. 수고하셨습니다.

1. 코드 품질 개선
2. 로그인 에러 메시지를 다른 방식으로 개선해 볼 것

2023-03-23 06:37 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +    }
이런건 addView로~

2023-03-23 06:41 UTC, honux77 approved these changes
여전히 Optional 의 사용이 미숙하지만 차차 좋아지겠죠...
또 변경 요청을 하고 싶긴 한데 일단 approve 하는 걸로
다음 단계에서 로그인쪽 코드 동료들에게 피어 리뷰를 한 번 받아봤으면 좋겠어요.

2023-03-23 06:41 UTC, merged

2023-03-23 07:15 UTC, ninaaano commented on src/main/java/kr/codesqaud/cafe/controller/MemberController.java
> +    }
addView에 들어있었는데 회원가입 -> 로그인으로 리다이렉트를 하니까 경로를 인식 못하고 405를 뱉어서 addViewController에서 뺐습니다ㅠㅠ 찾아보니까 WebMvcConfigurer에서 addViewController는 로직이 필요없는 간단한 맵핑에서 사용하는 것이 좋다고 하는데 아직 좋은 방법을 찾지 못했습니다ㅠㅠ