[Birdie] Step-5
codesquad-members-2023/be-java-cafe pull request #75
Opened 2023-03-23 11:50 UTC by birdieHyun

- 예외, 검증 처리를 하는데 어려움이 많았습니다. 검증하는 부분에서 중복 코드들이 많아보이고, 검증 클래스에서 repository를 의존해도 되는 것인가 의문이 들었지만 , 대안이 생각나지 않아 그대로 구현했습니다. 
- 오류, 검증 처리는 사용자가 입력하는 폼이 존재할 경우, 현재 페이지에서 사용자가 에러를 알아볼 수 있도록 구현하였고, 다른 예외의 경우 에러페이지로 이동하도록 하였습니다. 
- 예외페이지로 이동할 때, sendRedirect로 보내서 http 상태코드는 변경하지 않았습니다. 
- 6단계 진행 전 미흡한 테스트 코드 개선과 개념 강의를 들을 예정입니다.

2023-03-23 23:14 UTC, honux77 requested changes
머지 방지

2023-03-24 22:53 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/interceptor/CafeInterceptor.java
> +public class CafeInterceptor implements HandlerInterceptor {
```suggestion
public class LogInIntercepter implements HandlerInterceptor {
```
카페 인터셉터보다 조금 구체적인 이름이 좋을 것 같아요.

2023-03-24 22:55 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        model.addAttribute("user", new User());
여기에 비어 있는 유저를 추가하는데 필요한건지 모르겠어요.

2023-03-24 22:57 UTC, birdieHyun commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        model.addAttribute("user", new User());
<img width="681" alt="스크린샷 2023-03-25 오전 7 56 39" src="https://user-images.githubusercontent.com/115435784/227657941-f5c6d862-9e6c-4519-9d97-229b7989b9e0.png">

2023-03-24 22:58 UTC, birdieHyun commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        model.addAttribute("user", new User());
```
<div class="container" id="main">
   <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default content-main">
          <form name="question" method="post" action="/users/create" th:object="${user}">

              <div class="form-group">
                  <label for="userId">사용자 아이디</label>
                  <input th:errorclass="field-error" class="form-control" id="userId" name="userId" placeholder="User ID" th:value="${user.userId}">

                  <div class="field-error" th:errors="${user.userId}">
                      <p>아이디 오류</p>
                  </div>
              </div>

              <div class="form-group">
                  <label for="password">비밀번호</label>
                  <input th:errorclass="field-error" type="password" class="form-control" id="password" name="password" placeholder="Password">

                  <div class="field-error" th:errors="${user.password}">
                      <p>비밀번호 오류</p>
                  </div>

              </div>

              <div class="form-group">
                  <label for="name">이름</label>
                  <input th:errorclass="field-error" class="form-control" id="name" name="name" placeholder="Name" th:value="${user.name}">

                  <div class="field-error" th:errors="${user.name}">
                      <p>이름 오류</p>
                  </div>
              </div>

              <div class="form-group">
                  <label for="email">이메일</label>

                  <input th:errorclass="field-error" type="email" class="form-control" id="email" name="email" placeholder="Email" th:value="${user.email}">
                  <div class="field-error" th:errors="${user.email}">
                      <p>이메일 오류</p>
                  </div>
              </div>

              <button type="submit" class="btn btn-success clearfix pull-right">회원가입</button>
              <div class="clearfix" />
          </form>
        </div>
    </div>
</div>
```
form 에서 에러가 발생할 시 타임리프를 사용하기 위해 빈 객체를 추가해 주었는데, 이렇게 하는것도 타임리프에 의존하는 것인가요? 에러페이지로 이동시킬지 이렇게 타임리프를 사용하더라도 바로 에러 페이지를 보이게 할 지 고민하다가, 사용자의 편의성을 생각해서 타임리프를 사용하는 것으로 결정했는데, 좋지 않은 방법이라면 수정하겠습니다!

2023-03-24 23:02 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/validation/UserJoinValidator.java
> +public class UserJoinValidator implements Validator {
validator를 사용해서 유효성 검증을 했군요. 아주 좋습니다.
이런 경우 Repo에 의존성을 가지는 건 어쩔 수 없구요. 성능 저하의 요인이 되지만 당연하다고(?) 볼 수 있습니다.
그래서 다시 레디스 같은 캐시를 사용하거나 혹은 세션에 필요한 정보를 추가하거나 하는 등의 방법으로 Repo에서 읽어오는 성능저하를 극복하기도 하는데, 소규모 시스템에서는 DB도 충분히 빠르기 때문에 지금처럼 해도 무방합니다.

2023-03-24 23:04 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/validation/UserJoinValidator.java
> +public class UserJoinValidator implements Validator {
그럼데 유효성 검증은 크게 두 파트로 되어 있는데
1. 사용자 입력값 혹은 콘트롤러 매개변수의 값 자체가 유효한지 (null 체크, 타입 오류, 범위 검증 등) 
2. 진짜 데이터가 적합한지 (사용자와 글 일치 여부) 두 가지로 되어 있는데 두 가지를 별도로 분리하는게 조금 더 낫지 않을까 하는 생각이 드네요.

1의 경우 스프링의 어노테이션을 사용해서도 해결 할 수 있지만 직접 해 보는 것도 좋을 것 같습니다.

2023-03-24 23:06 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/domain/UserLoginDTO.java
> +public class UserLoginDTO {
DTO는 도메인에 속하지 않는 것 같은데요. DTO라는 별도의 패키지를 만들거나 필요한 다른 곳으로 옮기면 어떨까요? 
DTO를 만들었으면 DTO의 유무에 따른 장단점을 비교해 보는 것도 좋겠습니다.

2023-03-24 23:28 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
> +        return "error/error-page";
```suggestion
        return "error/error";
```

2023-03-24 23:31 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    public String updateUser(@PathVariable String userId, Model model) {
여기에도 UserValidator가 있어야하지 않을까요?

2023-03-24 23:33 UTC, honux77 approved these changes
👍

2023-03-24 23:38 UTC, birdieHyun commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    public String updateUser(@PathVariable String userId, Model model) {
``` java
    @GetMapping("/updateUser/{userId}")
    public String updateUser(@PathVariable String userId, Model model) {
        User user = memberRepository.findById(userId);

        model.addAttribute("user", user);
        return "users/update_user";
    }

    @PutMapping("/updateUser/{userId}")
    public String updateUserPost(@ModelAttribute User user, BindingResult bindingResult) {
        userUpdateValidator.validate(user, bindingResult);
        if (bindingResult.hasErrors()) {
            return "users/update_user";
        }


        memberRepository.updateUser(user);
        return "redirect:/users/list";
    }
```
update 할 때 update 형식에 맞는 올바른 입력 검증이 아닌, getmapping으로 user를 받으면서 올바른 접근인지 확인하는 validator를 추가해야 한다는 말씀이 맞을까요?

2023-03-25 00:53 UTC, merged