[ManJu] Step05 구현: 로그인 유무 체크 / 게시글 수정, 삭제 기능 구현
codesquad-members-2023/be-java-cafe pull request #81
Opened 2023-03-24 07:22 UTC by JeonHyoChang

## 고민했던 내용
- 지금 단계에서는 article의 외래키가 필요하지 않다고 생각되어서 없이 구현했으나, 오늘 강의를 통해 필요함을 느끼고 다음 과정에서 추가 해야 될것 같은 고민을 했습니다.
- 지금까지 서버를 노트북이 꺼지면 종료되었기에 nohup으로 바꿨으나, 요금 문제때문에 조금 걱정됩니다. ㄷㄷㄷ
- sql쿼리문의 적용 순서와 범위에 관하여 학습을 하니 좀더 정확하게 작동하는 쿼리문을 작성하도록 고민을 해야겠습니다!

## 설계 내용
- 스프링 인터셉터를 활용해 로그인의 유무를 체크해서, 비로그인 유저의 기능을 제한
- 개인정보 수정가능 여부 체크 기능을 재활용 하여 게시글 수정 체크를 설계
- 개인정보 수정 정보 전달 기능을 재활용 하여 업데이트와, 삭제 기능을 설계

## 느낀 점
- 테이블간의 기능이 비슷하기에 복붙후 수정하는 정도의 작업이라 나름 잘 진행된 느낌을 받았습니다. 설계의 중요성을 다시한번더 느낍니다.
- 중복되는 코드가 은근 많기에 이전 피드백의 내용처럼 따로 분리해서 관리할 필요성을 느낍니다 ㅠ

## aws 주소: http://13.55.133.135:8080/

2023-03-25 00:36 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/interceptor/LoginCheckInterceptor.java
> +        log.info("인증 체크 인터셉터 실행 {}", requestURI);
```suggestion
        log.debug("인증 체크 인터셉터 실행 {}", requestURI);
```

2023-03-25 00:37 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
> +                .order(1)
1 대신에 상수를 사용해 보세요.

2023-03-25 00:39 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +        User sessionUser = (User) session.getAttribute("loginUser");
loginUser 상수로 수정
그리고 같은 코드가 반복적으로 나오고 있습니다. 메소드 분리를 고려해 보세요.

2023-03-25 00:43 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +                .orElse(null);
orElseThrow 를 사용하고 예외처리를 하면 어떨까 하는 생각이 듭니다.

2023-03-25 00:45 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +                .orElse(null);
개인적인 생각입니다만 orElse(null) 은 조금 이상한 느낌이 들어요.

2023-03-25 00:49 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +        System.out.println(article.getId());
println????

2023-03-25 00:50 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +        article.setId(id);
여기도 본인글인지 검증하는 로직이 필요합니다.

2023-03-25 00:52 UTC, honux77 requested changes
6단계를 바로 하지 말고, 
- 코멘트 검토
- 코드 품질 개선
- 검증 로직 추가
를 해 주세요.

2023-03-27 05:30 UTC, JeonHyoChang commented
요구사항에 따른 개선 완료했습니다!!!

2023-03-27 06:51 UTC, honux77 commented
서비스를 추가하면서 같은 인터페이스의 구현체 클래스가 2개 이상 등록되어 @bean이 에러가 나서 찾아보고 @qualifier, @primary 어노테이션을 사용했습니다. 혹시 이 둘중에서 어떤것을 쓰는게 좋은지와, 이런상황을 안만드는것이 더 좋은지 궁금합니다! -> 아무 상관 없습니다. 이런 상황이 생기는 것도 자연스러운 현상압니다.


강의를 보면서 만든것중에 @SessionAttribute(name = "loginUser", required = false) User loginUser 라는 기능과 어떻게 동작하는지 알아 보았고, 이렇게 매개변수에서 미리 받는 방식과 HttpSession으로 내부에서 처리해서 사용하는 방식중에 어떤 것이 더 실무에 적합한지 궁금합니다.(현재는 SessionUtil의 활용을 위해 HttpSession으로 사용중입니다.)
--> 실무에는 보통 Spring Security를 씁니다. 둘 중 지금 단계에서 쓰기 편한 것 스스로 고민하고 사용하시면 됩니다.

2023-03-27 06:52 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/service/SessionUtil.java
> +    }
👍

2023-03-27 06:53 UTC, honux77 approved these changes

2023-03-27 23:42 UTC, merged