[이린] Step-5 : 권한확인 구현 / 게시글 수정, 삭제 구현
codesquad-members-2023/be-java-cafe pull request #97
Opened 2023-03-28 00:49 UTC by new-pow

## 변경사항
- 웹 페이지

2023-03-28 23:22 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/interceptor/AuthorityInterceptor.java
> +    public static final String[] LOGIN_INESSENTIAL = {"/", "/login", "/users/form", "/users/login", "/users/join"};
Path를 상수로 하니까 깔끔하고 좋은 것 같아요 ^^

2023-03-28 23:36 UTC, honux77 requested changes
게시글 업데이트 폼, 게시글 삭제, 게시글 업데이트 (PUT) 에서 본인 글인지 확인하는 부분이 안 보이는 것 같아요. 구현이 안 되어 있으면 추가로 구현해 주세요.

2023-03-29 00:58 UTC, new-pow commented
`AuthorityInterceptor`에 구현해두었습니다 @honux77

2023-03-29 01:08 UTC, honux77 commented on src/main/java/kr/codesqaud/cafe/interceptor/AuthorityInterceptor.java
> +    public void postHandle(HttpServletRequest request, HttpServletResponse response, Object handler, ModelAndView modelAndView) throws Exception {
오오 이거 참신한데요. 제가 잘 이해가 안 되는 부분이 있어서 이따 출근해서 물어볼게요.

2023-03-29 01:31 UTC, merged